global using AuditLogManager;
global using AuditLogManager.Controllers.Base;
global using AuditLogManager.Guids;
global using AuditLogManager.Infrastructure;
global using AuditLogManager.Infrastructure.Data;
global using AuditLogManager.Models;
global using EFCore.BulkExtensions;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
